### ISSUE TITLE
Разработка по промышленным стандартам

### ISSUE THREAD

**Issue by alehinsasha** [kasperiks/training1C#4]
- [x] Одна функциональность = одна фича и сценарии проверяющие работу этой фичи/функциональности
- [x] Использование фикстур
- [x] Повторное использование шагов (собственная библиотека шагов)
- [x] Фичи из воздуха
- [x] Детализация фичи

**Comment by alehinsasha** [comment]
**В дополнение к проверке навыка "Повторное использование шагов (собственная библиотека шагов)"**

Для подтверждения этого навыка у вас должно быть:
1. Две фичи проверяющие поступление и продажу товара.
2. В каталоге features каталог в котором вы будете хранить ваши библиотечные фичи.
3. В этом каталоге библиотечных шагов должна быть одна фича с одним универсальным (параметризованным) шагом который будет удалять документы.
4. В фичах поступления и продажи нужно использовать этот библиотечный шаг.

**Comment by kasperiks** [comment]
Здравствуйте, Александр.
В задании номер 4 выписали: 
Для подтверждения этого навыка у вас должно быть:
1. Две фичи проверяющие поступление и продажу товара.
2. В каталоге features каталог в котором вы будете хранить ваши библиотечные фичи.
3. В этом каталоге библиотечных шагов должна быть одна фича с одним универсальным (параметризованным) шагом который будет удалять документы.
4. В фичах поступления и продажи нужно использовать этот библиотечный шаг.

Фичу универсального шага я сделал и сгенерировал обработку, объясните как использовать эту обработку в сценарии закупки и в сценарии продажи?

**Comment by alehinsasha** [comment]
Например:

Допустим есть каталог features
И в нем есть две фичи
И в каталоге features есть каталог БиблиотечныеШаги
И в нем одна фича
И в этой фиче один шаг  **Я удаляю все документы вида "ИмяДокумента"**
Когда я в других фичах из каталога features напишу этот шаг
Тогда строка с этим шагом будет выделена серым цветом
И при выполнении будет использована процедура не из соответствующей выполняемой фиче обработке, а из обработки соответствующей "библиотечной" фиче.

**Comment by kasperiks** [comment]
Александр уточните пожалуйста в каком событии мне написать загрузку текстур?
Так как на данный момент при использовании события "ДокументыУдалилисьКорректно" загрузка текстур не происходит.
А нужное мне событие находится в обработке C:\repo\vanessa-behavior\features\Libraries\UITestRunner\step_definitions\РаботаСИнтерфейсом.epf

**Comment by alehinsasha** [comment]
Должно быть вы игры разрабатываете? Не **текстур** а **фикстур**, т.е. существующих данных. Только не подумайте что я "тролю", сам иногда думаю одно а пишу третье. Итак

> Александр уточните пожалуйста в каком событии мне написать загрузку текстур?

У сценария три условных секции: подготовка (допустим), действие (когда), результат (тогда). Секцию подготовки ещё называют контекстом сценария (не путать с контекстом фичи, который выполняеться перед каждым сценарием) вот в контексте сценария я подготовливаю инфобазу для сценария: удаляю, изменяю, создаю данные.

**Comment by kasperiks** [comment]
Александр мне удалось загрузить фикстуры.

Организовал загрузку фикстур в контексте сценария "Закупка товара" в событии Тогда документы удалились корректно.

Но проблема теперь в том что после выполнения метода Ванесса.ПродолжитьВыполнениеШагов(); обработчики не выполняются.
с чем может быть связано не подскажите?

**Comment by alehinsasha** [comment]
Закоммитьте что не получилось, я выкачаю ваш репо, воспроизведу у себя ошибку и подскажу что как.

**Comment by kasperiks** [comment]
Последние изменения закомичены, обработка называется     "АвтоматизацияПроцессаЗакупки.epf"

**Comment by alehinsasha** [comment]
Буду по ходу изучения проблемы писать замечания:

1) `ВызватьИсключение "Не реализовано.";` - в реализованном (законченном) шаге, этого текста быть не должно, т.к. этот текст при выполнении сценария дает статус шага "Ожидает реализации", а должен быть либо "Пройден" либо "Упал".

2) В одном шаге и удалять данные и загружать фикстуры - не рекомендую, т.к. с одной стороны можно вынести загрузку фикстур в отдельный шаг (я так и делаю) и это будет наглядно и просто, а с другой стороны (если все же в одном шаге делать и удаление и загрузку) нужно шаг назвать так чтобы отразить в нем два действия, а это уже не шаг.

3) Про асинхронность

> Но проблема теперь в том что после выполнения метода Ванесса.ПродолжитьВыполнениеШагов(); обработчики не выполняются.
> с чем может быть связано не подскажите?

Как сейчас: из процедуры проверки шага `ДокументыУдалилисьКорректно` переходим в `ЗагрузитьТекстурыИзМакета` в ней запрещаем выполнение шагов и создаем описание оповещения для перехода в `ЗагрузитьТекстурыИзМакетаЗавершение` а это серверная не экспортная процедура. Наверное вы ошиблись с именем процедуры обработки оповещения, не `ЗагрузитьТекстурыИзМакетаЗавершение` а `ЗагрузитьТекстурыИзМакетаЗавершениеКлиент`. Т.е. у вас не выполнялся метод для продолжения выполнения шагов.

**Comment by kasperiks** [comment]
Спасибо Александр за помощь. Да действительно ошибка была в том что я описал событие оповещения не той процедуры. Загрузка фикстур теперь отрабатывает и шаги выполняются до конца.
по поводу пункта 1 что можно написать вместо кода "Не реализовано"?

**Comment by alehinsasha** [comment]
> что можно написать вместо кода "Не реализовано"?

То что поможет вам понять где и при каких условиях (параметрах) произошла ошибка. Грубо говоря, когда вы на утро придете на работу после того как на ночь запустили прогон всех фич + allure, чтобы вы хотели увидеть, чтобы быстро сориентироваться и исправить ошибку.

**Comment by alehinsasha** [comment]
готово!
